#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | PlatformOne | bundle | artifacts' 
  hosts: containerone
  vars_files:
    - '../p1.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
  vars:
    module: "bundle"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    redhat_quay_pull_file: '{{ dir_artifacts }}/.docker/master.json }}'
  tasks:
    - name: '{{ ansible_name_module }} | stage registry startup assets' 
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - { src: '{{ dir_git_bundle }}/templates/bin/registry.sh', dest: '/tmp/registry.sh' }
        - { src: '{{ dir_git_bundle }}/templates/registry2/registry.yml', dest: '/tmp/registry.yml' }
  roles:
    - bundle
