---
####### Check if lock file for image pull
####### - NOTE: lock file intended for oc image mirror --to-dir may be disposable with skopeo code
- name: '{{ ansible_name_module }} | stat | check for mirror v2.sha256'
  stat:
    path: '{{ dir_one }}/mirror/v2.list.sha256'
  register: mirror_sha_check

###### Download OpenShift Docker Images from Quay.io to File: /root/PlatformOne/Mirror/v2
- name: '{{ ansible_name_module }} | block | Download OpenShift images'
  block:

  ######### Purge & Prepare
    - name: '{{ ansible_name_module }} | file:absent | Purge pre-existing content'
      file:
        path: "{{ dir_one }}/mirror"
        state: absent
    - name: '{{ ansible_name_module }} | file:directory | Create mirror artifact directories'
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ dir_one }}/mirror"

  ######### Mirror Images to directory
    - name: '{{ ansible_name_module }} | command:skopeo.copy | Sync content from quay.io'
      command:
        argv:
          - skopeo
          - copy
          - docker://quay.io/{{ item }}
          - docker://localhost:5500/{{ item }}
          - --additional-tag
          - 'quay.io/{{ item }}'
        creates: "{{ dir_one }}/mirror/docker/registry/v2/repositories/openshift-release-dev/ocp-release"
      with_items:
        - "{{ lookup('file', '/var/lib/trno/release.list') }}"

  ####### Lock File Conditional
  when: not mirror_sha_check.stat.exists
###### END OF BLOCK #######

####### Place lock file for image pull
####### - NOTE: lock file intended for oc image mirror --to-dir may be disposable with skopeo code
- name: '{{ ansible_name_module }} | stat | sha256 mirror/v2 directory list'
  shell: 'find -type f ! -iname "sha256checksums" -exec sha256sum "{}" + > {{ local_home }}/PlatformOne/mirror/v2.list.sha256'
