---
####### Download CloudCTL Pod Images
- name: '{{ ansible_name_module }} | file:directory | mkdir images target path' 
  file: 
    path: "{{ dir_one }}/images"
    state: absent
  file: 
    path: "{{ dir_one }}/images"
    state: directory

- name: '{{ ansible_name_module }} | git:clone | Clone Git Dependencies' 
  command:
    argv:
      - skopeo
      - copy
      - docker://{{ item.uri }}
      - docker-archive://{{ item.path }}/{{ item.name }}.tar
    creates: "{{ item.path }}/{{ item.name }}.tar"
  with_items:
    - "{{ images_cloudctl }}"
