---
####### Download CloudCTL Pod Images
- name: '{{ ansible_name_module }} | file:directory | mkdir images target path' 
  file: 
    path: "{{ dir_one }}/images"
    state: absent
  file: 
    path: "{{ dir_one }}/images"
    state: directory

- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull CloudCTL Pod Images' 
  command:
    argv:
      - skopeo
      - copy
      - docker://{{ item.uri }}/{{ item.name }}:{{ item.tag }}
      - docker-archive://{{ item.path }}/docker-image-{{ item.name }}-{{ item.tag }}.tar
      - --additional-tag
      - '{{ item.name }}:{{ item.tag }}'
    creates: "{{ item.path }}/{{ item.name }}.tar"
  with_items:
    - "{{ images_cloudctl }}"
