---
- name: '{{ ansible_name_module }} | stage registry startup assets' 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '{{ dir_git_bundle }}/templates/bin/registry.sh', dest: '/tmp/registry.sh' }
    - { src: '{{ dir_git_bundle }}/templates/registry2/registry.yml', dest: '/tmp/registry.yml' }
