#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "images"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: "{{ ansible_name_module }} | unarchive:openshift-client-linux.tar.gz | Downloading OC Client {{ openshift_version }}"
      unarchive:
        remote_src: yes
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-client-linux.tar.gz"
        dest: '{{ dir_bin }}'
        mode: 0775

    - name: '{{ ansible_name_module }} | command:cmd | Test Binaries'
      command:
        cmd: '{{ item.bin }} {{ item.exec }}'
      with_items:
        - { bin: '{{ dir_bin }}/oc',  exec: 'version --client' }
